CREATE TABLE `commercial_data` (
  `no` int NOT NULL AUTO_INCREMENT COMMENT '상가업소번호',
  `shopname` varchar(45) DEFAULT NULL COMMENT '상호명',
  `localname` varchar(45) DEFAULT NULL COMMENT '지점명',
  `code1` varchar(45) DEFAULT NULL COMMENT '상권업종대분류코드',
  `codename1` varchar(45) DEFAULT NULL COMMENT '상권업종대분류명',
  `code2` varchar(45) DEFAULT NULL COMMENT '상권업종중분류코드',
  `codename2` varchar(45) DEFAULT NULL COMMENT '상권업종중분류명',
  `code3` varchar(45) DEFAULT NULL COMMENT '상권업종소분류코드',
  `codename3` varchar(45) DEFAULT NULL COMMENT '상권업종소분류명',
  `code4` varchar(45) DEFAULT NULL COMMENT '표준상업분류코드',
  `codename4` varchar(45) DEFAULT NULL COMMENT '표준산업분류명',
  `citycode` varchar(45) DEFAULT NULL COMMENT '시도코드',
  `city` varchar(45) DEFAULT NULL COMMENT '시도명',
  `gucode` varchar(45) DEFAULT NULL COMMENT '시군구코드',
  `gu` varchar(45) DEFAULT NULL COMMENT '시군구명',
  `dongcode` varchar(10) DEFAULT NULL,
  `dong` varchar(45) DEFAULT NULL COMMENT '법정동명',
  `jibuaddress` varchar(45) DEFAULT NULL COMMENT '지번주소',
  `address` varchar(45) DEFAULT NULL COMMENT '주소',
  `oldpostcode` varchar(45) DEFAULT NULL COMMENT '예전우편번호',
  `postcode` varchar(45) DEFAULT NULL COMMENT '우변번호',
  `lng` varchar(45) DEFAULT NULL COMMENT '경도',
  `lat` varchar(45) DEFAULT NULL COMMENT '위도',
  PRIMARY KEY (`no`)
) ENGINE=InnoDB AUTO_INCREMENT=28524866 DEFAULT CHARSET=utf8 COMMENT='상권정보'